### ISSUE TITLE
Add "&enablejsapi=1" to URL string

### ISSUE THREAD

**Issue by dancollings** [dartiss/youtube-embed#49]
Is there a way to add "&enablejsapi=1" to the output URL string in the iFrame so that all videos can be targetted and controlled with YouTube's iFrame API javascript?

**Comment by dancollings** [comment]
Bumping this - any luck?

**Comment by dancollings** [comment]
@dartiss

**Comment by dartiss** [comment]
This isn't a support forum but a place to add issues or request enhancements - please ask this question in the WordPress.org support forum for the plugin.
