### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function wp_kses()

### ISSUE THREAD

**Issue by terabitsoft** [dartiss/youtube-embed#79]
Hi,

Started getting error after updating to the latest version of the plugin. Quick support is highly appreciated.

Fatal error: Uncaught ArgumentCountError: Too few arguments to function wp_kses(), 1 passed in /home/www/help.mydomain.com/wp-content/plugins/youtube-embed/includes/add-scripts.php on line 173 and at least 2 expected in /home/www/help.mydomain.com/wp-includes/kses.php:731 Stack trace: #0 /home/www/help.mydomain.com/wp-content/plugins/youtube-embed/includes/add-scripts.php(173): wp_kses('\n') #1 /home/www/help.mydomain.com/wp-includes/class-wp-hook.php(287): youtube_embed_add_to_head('') #2 /home/www/help.mydomain.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /home/www/help.mydomain.com/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /home/www/help.mydomain.com/wp-includes/general-template.php(2884): do_action('wp_head') #5 /home/www/help.mydomain.com/wp-content/themes/myappHelp1/templates/front_1.php(31): wp_head() #6 /home/www/help.mydomain.com/wp-content/themes/myappHelp1/functions.php(1229): require_once('/home/www/help....') #7 /home/www/help.mydomain. in /home/www/help.mydomain.com/wp-includes/kses.php on line 731
There has been a critical error on your website.

**Comment by dartiss** [comment]
Was not supplying a second parameter. However, it was the wrong escaping method - have switched to another.
